#!/usr/bin/env bash
#
# validate the .cqfdrc syntax

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

cqfdrc_old=$(mktemp)
cp -f .cqfdrc "$cqfdrc_old"
echo "foo	=bar" >>.cqfdrc

#
# Legacy syntax
#
jtest_prepare "cqfdrc with tabulation before should not pass"
if ! "$cqfd" run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f "$cqfdrc_old" .cqfdrc
echo "foo=	bar" >>.cqfdrc

jtest_prepare "cqfdrc with tabulation after should not pass"
if ! "$cqfd" run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f "$cqfdrc_old" .cqfdrc
echo "foo =bar" >>.cqfdrc

jtest_prepare "cqfdrc with space before should not pass"
if ! "$cqfd" run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f "$cqfdrc_old" .cqfdrc
echo "foo= bar" >>.cqfdrc

jtest_prepare "cqfdrc with space after should not pass"
if ! "$cqfd" run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f "$cqfdrc_old" .cqfdrc
echo "command=\"echo \\
	foo=bar \\
	baz=qnux\"
" >>.cqfdrc

#
# Syntax
#
jtest_prepare "cqfdrc with multiline should pass"
if $cqfd | grep 'foo=bar baz=qnux'; then
	jtest_result pass
else
	jtest_result fail
fi

mv -f "$cqfdrc_old" .cqfdrc
