name: Debian Packaging
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install bash-completion build-essential debhelper devscripts pkgconf shellcheck
    - name: Build package
      run: |
        cd ${{ github.event.repository.name }}
        dpkg-buildpackage -us -uc
        cd ..
    - name: Lint package
      run: |
        # FIXME:
        # E: cqfd: extended-description-is-empty
        # E: cqfd: no-copyright-file
        # E: cqfd: shell-script-fails-syntax-check [usr/share/bash-completion/completions/cqfd]
        # W: cqfd: bash-completion-with-hashbang /bin/sh [usr/share/bash-completion/completions/cqfd:1]
        # W: cqfd: description-synopsis-starts-with-article
        # W: cqfd: no-manual-page [usr/bin/cqfd]
        # lintian *.deb
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        path: |
          *.deb
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          *.deb
